/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_valeriykundas_eyedetectornew_OpenCVNativeClass */

#ifndef _Included_com_valeriykundas_eyedetectornew_OpenCVNativeClass
#define _Included_com_valeriykundas_eyedetectornew_OpenCVNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_valeriykundas_eyedetectornew_OpenCVNativeClass
 * Method:    faceDetection
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_valeriykundas_eyedetectornew_OpenCVNativeClass_faceDetection
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
